docs/index.md
That's the page that will be shown when going to https://docs.northstar.tf/
This version is pretty bare bones and just so that we have something there instead of a 404. Improvements are more than welcome.
=> Add initial main landing page

docs/Modding/reference/respawn/clientcommands.md
=> Fix typo in code example

docs/Modding/reference/respawn/dialog.md
leftover from the old moddingdocs that had trailing spaces
=> Remove trailing spaces inside quotation marks

docs/Modding/reference/respawn/hud_element_notation.md, docs/Modding/reference/respawn/native_server/damageinfo.md
There were some leftover snippets that were overlooked in #2
=> Convert leftover reStructuredText syntax to Markdown

docs/Modding/guides/tools/tools.md
The repo it links to (https://github.com/EM4Volts/tf-2_substance_maker) was set to private while a better version is being worked on.
There's not really a point in linking to a page that cannot be accessed anyway, so it should be fine to remove for now so that we can get the dead link checker (#6) added until the new version is out ^^
=> Remove link to private repo from tools page

docs/Modding/squirrel/index.md
The publisher of the extension renamed themselves, resulting in a broken link.
See also https://github.com/R2Northstar/ModdingDocs/pull/250 for context.
=> Fix link to Respawn Squirrel vscode extension

docs/Modding/guides/tools/tools.md
Removes link to https://github.com/squidgyberries/RSPNVPK which is no longer available and poking the owner of the repo in #47 resulted in no response.
Closes #47
=> Remove broken link to RSPNVPK fork that is no longer available

docs/Wiki/development/README.md, docs/Wiki/hosting-a-server-with-northstar/dedicated-server/hosting-on-linux.md, docs/Wiki/installing-northstar/basic-setup.md, docs/Wiki/steamdeck-and-linux/installing-on-steamdeck-and-linux.md
For README.md files, GitBook allowed for just linking the path that the file was at. MkDocs does not allow that so the links need to be updated.
=> Fix broken internal wiki links

docs/Wiki/hosting-a-server-with-northstar/server-settings/file-names.md
Adds the missing headers back to the file names page that got lost in https://github.com/R2Northstar/NorthstarWiki/pull/218
=> Re-add missing headers

.github/workflows/build.yml
Build in CI with strict mode to ensure that CI fails if there are any warnings. This is done to catch issues in PRs before merging them.
=> Build in CI with strict mode

docs/Wiki/README.md, docs/Wiki/development/contributing-code-to-northstar.md, docs/Wiki/development/repositories/northstarlauncher.md, docs/Wiki/development/testing.md, docs/Wiki/installing-northstar/northstar-installers/README.md
Convert link embeds from GitBook syntax to MkDocs syntax excluding YouTube videos which will be handled separately.
=> Convert link embeds from GitBook syntax to MkDocs syntax

docs/Wiki/README.md, docs/Wiki/development/README.md, docs/Wiki/development/reviewing.md, docs/Wiki/faq.md, docs/Wiki/installing-northstar/basic-setup.md, docs/Wiki/installing-northstar/manual-installation.md
Rewrite sections containing GitBook styled internal links as there's no MkDocs replacement for it. Instead just reformat them to standard internal links and integrate them in the existing text.
=> Rewrite sections containing GitBook styled internal links

docs/Modding/guides/gettingstarted.md, docs/Wiki/faq.md, docs/Wiki/hosting-a-server-with-northstar/dedicated-server/hosting-on-linux.md, docs/Wiki/hosting-a-server-with-northstar/troubleshooting.md, docs/Wiki/other/helping.md, docs/index.md
Change all links from `r2northstar.gitbook.io` to internal links in the docs and adjust text accordingly.
As we transferred content from the old GitBook Wiki into the NorthstarDocs (this repo).
=> Change all links from old GitBook to internal links

docs/Wiki/other/helping.md
Change mentions of the Spectre bot to Reaper as it has since been forked and renamed.
Closes #95
=> Change mentions of the Spectre bot to Reaper

docs/Modding/guides/tools/rpakmodding.md
As it's just nicer to read
> The assets in the `.rpak` file are kept [...]
vs
> The assets in the .rpak file are kept [...]
=> Format file type suffix as inline code

docs/Wiki/README.md
The link to the source code was still pointing directly to the website which is a leftover from when we didn't have a website yet.
=> Link to GitHub for source code

mkdocs.yml
Sets a default description to be shown in embed previews.
Example:
Closes #110
=> Define default site description

mkdocs.yml
https://squidfunk.github.io/mkdocs-material/reference/footnotes/
Adds support for rendering markdown footnotes like
> Hi from text[^1]
> [^1]: Hi from footnote
The syntax for which is:
```
Hi from text[^1]
[^1]: Hi from footnote
```
=> Enable rendering footnotes

docs/Wiki/steamdeck-and-linux/installing-on-steamdeck-and-linux.md
I recently installed Northstar on Linux (Arch) & thought the instructions could be clearer
Turns out the guide had proper sub-items in it's list
Looked good in GitHub web view, [livemarkdownpreview](https://livemarkdownpreview.com) & [glow](https://github.com/charmbracelet/glow)
Only the generated site had flattened the instructions into a single list
Mostly just had to tighten up the indentation
Starting on a `*` indent then following with numbered points also broke (became all dots)
For those I just made the parent point multi-line (matching indent + double spaces at end of previous line)
Generated site uses letters for children, web markdown viewers use roman numerals
Not bothered to fix that, but it's probably important to note
The third tier children (NorthstarProton > Manual > Steam …
=> Clean up Linux Install Guide

.github/.markdownlinkcheck.json
These two links fail in the linkcheck CI even though the pages behind them are accessible. As such we just whitelist them so that CI stops failing.
=> Whitelist working links that fail linkcheck

docs/Wiki/using-northstar/vanilla.md
Now points to the new thunderstore page and github repository
=> Update outdated Vanilla+ links

.github/workflows/linkcheck.yml
Adds entry to config to run linkcheck once a week to catch any links that may have broken in the meantime.
=> Run linkcheck periodically

docs/stylesheets/extra.css
Removes the hardcoded styling that forces the code sections background to be dark even in light mode.
Closes #61
=> Remove hardcoded background colour

docs/Modding/guides/tools/VTFModding.md
Adds a direct link to the Valve dev wiki that shows a few material proxies exclusive to Titanfall
=> Add direct link to Titanfall material proxies

.github/.markdownlinkcheck.json, .github/workflows/linkcheck.yml
Since the one previously used
(gaurav-nelson/github-action-markdown-link-check) is deprecated, we switch to the tcort maintained fork of the action.
=> build: Update CI link checking action

docs/Wiki/steamdeck-and-linux/installing-on-steamdeck-and-linux.md, docs/Wiki/steamdeck-and-linux/linux-troubleshooting.md
NorthstarProton has not been maintained in over a year and everyone involved with it has stopped working on it.
GE-Proton provides all the needed functionality to run Northstar without having to fiddle with anything while also being actively maintained.
=> Replace NorthstarProton with GE-Proton in Linux section
