- .github/workflows/build.yml
Build docs on push without deploying, simply to test that the build process has not been broken by a commit
> Build docs on push

- docs/Modding/guides/scripting/custommenus.md
- docs/Modding/guides/scripting/gamemodemods.md
- docs/Modding/guides/tools/MDLModding.md
- docs/Modding/guides/tools/VTFModding.md
- docs/Modding/plugins/interfacesapi.md
- docs/Modding/reference/northstar/chathooks.md
- docs/Modding/reference/northstar/httprequests.md
- docs/Modding/reference/respawn/damagehistory.md
- docs/Modding/reference/respawn/entities.md
- docs/Modding/reference/respawn/hud_element_notation.md
- docs/Modding/reference/respawn/hud_menus.md
- docs/Modding/reference/respawn/hud_script.md
- docs/Modding/reference/respawn/native_server/damageinfo.md
- docs/Modding/reference/respawn/topology.md
- docs/Modding/squirrel/async.md
- docs/Modding/squirrel/networking.md
Ensures that only spaces are used for indentation as that was already the most common case before this PR.
> Ensure consistent whitespaces

- .github/workflows/formatting.yml
Checks for tabs and fails if any are detected.
> Add Action to check for mixed whitespaces

- docs/Modding/guides/contributing.md
- docs/Modding/index.md
in regards to the switch from reStructedText to Markdown
> Update contributing documentation

- docs/Modding/squirrel/async.md
- docs/Modding/squirrel/index.md
as it's the official name for Respawn's Squirrel fork
> Change all mentions of rSquirrel to squirrel_re

- docs/Modding/guides/keyvalue/localisation.md
Supersedes https://github.com/R2Northstar/ModdingDocs/pull/249
> Added Polish to the list of natively supported languages by Titanfall 2

- docs/Modding/guides/keyvalue/weaponkeyvalues.md
> Fix broken link to keyvalue modding page

- docs/Modding/guides/scripting/gamemodemods.md
> Fix typo in creating gamemodes page

- docs/Wiki/hosting-a-server-with-northstar/server-settings/file-names.md
Adds missing newline so that the table renders properly in MkDocs
> Fix broken table

- docs/Wiki/hosting-a-server-with-northstar/server-settings/file-names.md
`File names` vs `Name in the files`
> Ensure page title matches version in old wiki

- docs/Modding/guides/tools/MDLModding.md
- docs/Modding/reference/respawn/damagehistory.md
- docs/Modding/reference/respawn/native_server/damageinfo.md
There were two more links two headers that were still broken either from the transfer or from even before transferring.
> Fix broken header links in Modding section of Docs

- mkdocs.yml
- poetry.lock
- pyproject.toml
using [mkdocs-video](https://pypi.org/project/mkdocs-video/).
> Add dependency to render YouTube video embeds

- docs/Wiki/README.md
- docs/Wiki/hosting-a-server-with-northstar/getting-started.md
- docs/Wiki/installing-northstar/manual-installation.md
- docs/Wiki/installing-northstar/northstar-installers/README.md
Convert YouTube embeds from GitBook syntax to MkDocs syntax
> Convert YouTube embeds from GitBook syntax to MkDocs syntax

- docs/Modding/guides/tools/MDLModding.md
- docs/Modding/mapping/info-dump.md
as it's less verbose and is already used in other places on the wiki as well
> Convert iframe YouTube embeds to mkdocs-video syntax

- README.md
by making the title not ModdingDocs specific and explaining the partitioning between Wiki and Modding sections.
> Adjust README for combined docs

- README.md
Use common markdown syntax for formatting headers in main README
> Use common markdown syntax for formatting headers

- README.md
> Mention fix for building on Windows

- docs/Wiki/development/repositories/atlas.md
> Fix typo in Atlas page

- docs/Modding/guides/tools/rpakmodding.md
`gettingstarted` -> `[Getting Started](../gettingstarted.md)`
> Fix broken link on Rpak Modding page

- docs/Modding/reference/respawn/rui_args.md
Contains a page with arguments for all(?) RUI instances in the form of structs.
Taken from the NS discord, original list made by Spoon.
> Add an RUI Arguments Dump

- docs/Wiki/development/repositories/README.md
- docs/Wiki/hosting-a-server-with-northstar/basic-listen-server.md
- docs/Wiki/hosting-a-server-with-northstar/dedicated-server/best-practices.md
- docs/Wiki/other/credits.md
- docs/Wiki/other/moderation/rules.md
- docs/Wiki/using-northstar/server-browser.md
``NorthstarWiki`` -> ``NorthstarDocs``
> Update ``NorthstarWiki`` links

- docs/Modding/reference/respawn/hud_script.md
Add `void Hud_SetPinSibling( var elem, string sibling_name )` to Element Position
```markdown
!!! cpp-function "void Hud_SetPinSibling( var elem, string sibling_name )"
Only change the sibling pinned to
```
> Add mention of `Hud_SetPinSibling()` function

- docs/Wiki/hosting-a-server-with-northstar/basic-listen-server.md
- docs/Wiki/hosting-a-server-with-northstar/dedicated-server/README.md
Relates to https://github.com/R2Northstar/NorthstarLauncher/pull/536
Supercedes https://github.com/R2Northstar/NorthstarWiki/pull/307
> Warn people who are hosting a server that their mod names will be shown

- .github/.markdownlinkcheck.json
Sort the list of whitelisted links alphabetically so that it's clearer at which location to insert new links to.
> Sort whitelisted links alphabetically

- .github/dependabot.yml
Adds a dependabot config to automatically create PRs for outdated Python packages
> Add dependabot config for updating Python packages

- docs/Wiki/development/debugging/visualstudio.md
~~Fixed a typo and~~ hopefully fixed the misaligned image (couldn't verify since I had issues with running the powershell script and I can't be bothered to troubleshoot it for such a small change)
> Fix alignment in Visual Studio section

- docs/Wiki/development/repositories/northstarmods.md
Explains how to merge with automatically resolving merge conflicts after pushing vanilla file.
> Explain how to merge after committing vanilla file

- docs/Modding/guides/gettingstarted.md
Document the option to create ConCommands in `mod.json`
> Document ConCommands in `mod.json`

- docs/Modding/guides/tools/MDLModding.md
- Fixes typos
- Adds info about RUI meshes
- Adds info about Crakokalos studiomdl (closes https://github.com/R2Northstar/NorthstarDocs/issues/131)
- Add info about the extra model types ( _stow, _menu, _projectile )
- Adds extra erros to the common issues section
I've had these changes saved locally for a while and completely forgot to commit them lol
> Revamp MDL modding page

- docs/Wiki/development/repositories/northstarmods.md
Follow-up PR of https://github.com/R2Northstar/NorthstarDocs/pull/142:
- reorganizes the article;
- adds statement about end-of-line sequence;
- adds an example listing git commands.
> Improve vanilla file commit article

- docs/Modding/guides/keyvalue/index.md
- Fixed some small typos
- Separated the second paragraph so its a bit easier to understand
- Added crash warning when trying to modify custom weapons using keyvalues
> Update keyvalue index page

- docs/Modding/guides/tools/MDLModding.md
No idea how the hell i even missed that
> Fix MDL modding page mentioning the wrong VPK

- docs/Modding/plugins/index.md
- docs/Modding/plugins/interfaces.md
- docs/Modding/plugins/required-interfaces.md
Replace this line with a short description of your change.
> Plugin Clarifications

- mkdocs.yml
- pyproject.toml
- uv.lock
Add mermaid dependency to pyproject.
> Add mermaid dependency

- docs/Modding/guides/tools/ShaderModding.md
Adds a page based on how to Modify existing and make new Shaders inside of the rpak system.
> Add Shader docs
